### ISSUE TITLE
Overview of Project

### ISSUE THREAD

**Issue by sptorvi** [hackforla/racial-justice#4]
### Overview
Create an overview of the project to plan for the further steps

### Action Items

- [ ] Create and execute a research plan -Defining partnership assessment variables & metrics: understanding priorities in collecting information issue #3 **(Estimated Hours: 20)** 
- [ ] Screening the market: conducting competitive intelligence to gain an insight into partnership opportunities and operating models **(Estimated Hours: 100 - 200 company estimate)** 
- [ ] When there is a concrete list of all qualified immunity player companies in the US **(Estimated Hours: 20)**
   - [ ] Rank companies based off of the following:
       - [ ] identifying key KPIs for Hack for LA 
       - [ ] externally focused KPIs - size of positive impact on the US.
- [ ] Piece together an email template from Bonnie's IJ email chain (sequence based?) **(Estimated Hours: 5)**
- [ ] look at all technical positions on the identified companies website and send out email template one by one **(Estimated Hours: 2-20)**

**Comment by cj98123** [comment]
Updated the final steps and inputted time estimates
