### ISSUE TITLE
One sheet

### ISSUE THREAD

**Issue by ExMember** [hackforla/racial-justice#7]
Write a one-sheet for the project including milestones for the next 6 months.

### Action Items

- [x]  Review Civic Opportunity one-sheet
- [x]  Review another project example one-sheet
- [x]  Produce First Draft of One-Sheet
- [x]  Prepare questions for review with Bonnie

### Resources/Instructions
[Racial Justice one sheet](https://docs.google.com/document/d/10hjsR7EjVpL-P18eCGjgLMKD5DtT1gwibnmHXzLTcSE/edit?pli=1)

[All Project One Sheets](https://github.com/hackforla/product-managment/issues/3)
[VRMS Doc](https://docs.google.com/document/d/1lsRUAAMs1b60LOqQb9H6c4Ky9AbQ7QN4FB1XNErKxEs/edit)
[Civic Opportunity Project One-Sheet](https://github.com/hackforla/civic-opportunity/blob/master/Civic_Opportunity_Project_OnePage.pdf)

Example from Youth Justice Nav
[project proposal](https://docs.google.com/document/d/1OsNZzwumWmzJidN8ER-JrOV8-UcJBhjhob1HkSNp7Jg/edit)
[one sheet](https://docs.google.com/document/d/1NKcYSoGW2SNUrf-_osyBS9HKK7oUH7c8oQIgb5o8n2U/edit)

**Comment by ExMember** [comment]
Draft one sheet https://docs.google.com/document/d/1IG6KiUlBBznom_JbqKM_nQJkPBs-qgCv4zizdox67tY/edit

**Comment by nomingantulga** [comment]
here is a new draft one sheet: 

https://docs.google.com/document/d/10hjsR7EjVpL-P18eCGjgLMKD5DtT1gwibnmHXzLTcSE/edit?pli=1

Also, here is an issue coinciding with the project one sheet for Racial justice: https://github.com/hackforla/product-management/issues/57

**Comment by ExperimentsInHonesty** [comment]
save this for creating an ipsec 
Collect information that will allow us to determine impact and effectiveness of organizations working in qualified immunity

**Comment by ExperimentsInHonesty** [comment]
@nomingantulga 
- [x] Make a new issue for Product Roadmap
   - [x] include comment above about ipsec with the details
- [x] Add a link to this one sheet to the [quicklinks card](https://github.com/hackforla/racial-justice/projects/1#card-40894546) 
- [x] Close this issue

**Comment by ag2463** [comment]
@ExperimentsInHonesty   
To make a new issue for the Product Roadmap, do you mean:
Add an additional line on the One Sheet with the ipsec comment
or
Create a new blank issue and label it Product Roadmap and put it in the icebox with the ipsec comment

**Comment by ExperimentsInHonesty** [comment]
@ag2463 this one: Create a new blank issue and label it Product Roadmap and put it in the icebox with the ipsec comment
